/*************************************************
Initially Generated by SSoT.me - 2017
    EJ Alexandra - An odxml42 Tool
    This file WILL NOT be overwritten once changes are made.
*************************************************/
using System;
using System.Collections.Generic;
using System.ComponentModel;
using GwPlatformDotNet.Lib.Enums;


namespace GwPlatform.Lib.DataClasses
{
    [Serializable]
    public partial class GNodeRole
    {
        public GNodeRole()
        {
            this.InitPoco();
        }
       static GNodeRole()
        {
            GNodeRole.PopulateAllGNRs();
        }
        public override String ToString()
        {
            return String.Format("GNodeRole: {0}", this.Name);
        }

        public FuzzyLogicEnum HasAgentEnum { get; private set; }

        public FuzzyLogicEnum ElectricallyConnectsAndDisconnectsEnum { get; private set; }

        public FuzzyLogicEnum HasVoltageEnum { get; private set; }
        public Nullable<DateTime> IRLCreatedAtUTC { get; set; }
        public static List<GNodeRole> AllGNRs { get; private set; }

        public static Dictionary<GNodeRoleEnum, GNodeRole> GNRsByEnum { get; private set; }
        public static Dictionary<String, GNodeRole> GNRsByName { get; private set; }

 

    }
}