/*************************************************
Initially Generated by SSoT.me - 2017
    EJ Alexandra - An odxml42 Tool
    This file WILL NOT be overwritten once changes are made.
*************************************************/
using System;
using System.Collections.Generic;
using System.ComponentModel;
using GwPlatformDotNet.Lib.Enums;
using System.Linq;


namespace GwPlatform.Lib.DataClasses
{
    [Serializable]
    public partial class GNodeRole
    {
        public GNodeRole()
        {
            this.InitPoco();
        }

        public FuzzyLogic HasAgent { 
            get{
                return FuzzyLogic.AllFuzzyLogics.FirstOrDefault(firstFL => this.HasAgentValue == firstFL.Value);
            }
        
        }
        // TODO ONE: HasAgentDerived as a field means create HasAgent with the type of HasAgentDerived using HasAgentValue
        // TODO: create a test that fails if this.HasAgentValue is not a subset of FuzzyLogic.AllFuzzyLogicValues 
        // That allows HasAgentValue to be null ... but if it is populated it must
        // be in the FuzzyLogic.AllFuzzyLogicValues list.

        public FuzzyLogic ElectricallyConnectsAndDisconnects {
            get{
                return FuzzyLogic.AllFuzzyLogics.FirstOrDefault(firstFL => this.ElectricallyConnectsAndDisconnectsValue == firstFL.Value);
            }      
        }

        public FuzzyLogic HasVoltage { 
            get{
                return FuzzyLogic.AllFuzzyLogics.FirstOrDefault(firstFL => this.HasVoltageValue == firstFL.Value);
            }      
        }
       static GNodeRole()
        {
            GNodeRole.PopulateGNodeRoles();
        }
        public override String ToString()
        {
            return String.Format("GNodeRole: {0}", this.Value);
        }
        public Nullable<DateTime> IRLCreatedAtUTC { get; set; }
        public static List<GNodeRole> AllGNRs { get; private set; }


 

    }
}