/*************************************************
Initially Generated by SSoT.me - 2017
    EJ Alexandra - An odxml42 Tool
    This file WILL NOT be overwritten once changes are made.
*************************************************/
using System;
using System.ComponentModel;
using System.Collections.Generic;
using GwPlatformDotNet.Lib.Enums;
                        
namespace GwPlatform.Lib.DataClasses
{                   
    
    public partial class GNodeStatus 
    {
        public GNodeStatus()
        {
            this.InitPoco();
        }



        public override String ToString()
        {
            return String.Format("GNodeStatus: {0}", this.Name);
        }
                            
    }
}